print-5-numbers: &print-5-numbers
  - echo 1
  - echo 2
  - echo 3
  - echo 4
  - echo 5
  
pipelines:
 name: foo
 steps:
   - name: foo
     type: Bash
     execution:
       onExecute:
         - *print-5-numbers
 
