resources:
  - name: myFileSpecRes
    type: FileSpec
    configuration:
      sourceArtifactory: myArtifactory
      pattern: "folder1/folder2/example-*.tar.gz"
      recursive: false
      flat: true
      
  - name: myRepo
    type: GitRepo
    configuration:
      path: deepikasl/vt1
      gitProvider: myGithub
      branches:
        include: ^{{gitBranch}}$
        
  - name: environmentVariableBag
    type: PropertyBag
    configuration:
      tarVersion: ""
      serverName: ""

pipelines:
  - name: producing_pipeline
    steps:
      - name: first_step
        type: Bash
        configuration:
          inputResources:
            - name: myRepo
          outputResources:
            - name: myFileSpecRes
            - name: environmentVariableBag
        execution:
          onExecute:
            - pushd $res_templateGit_resourcePath
            - echo "some logic to produce tarball"
            - TAR_FILENAME="example-{{gitBranch}}.tar.gz"
            - ./tar/build.sh $TAR_FILENAME
            - jfrog rt upload bin/$TAR_FILENAME folder1/folder2/$TAR_FILENAME #uploading to artifactory
            - write_output environmentSetupBag "tarVersion=${run_number}" # this will update the propertyBag resource
            - write_output environmentSetupBag "serverName=someName"

  - name: consuming_pipeline
    steps:
      - name: second_step
        type: Bash
        configuration:
          inputResources:
            - name: myFileSpecRes
            - name: environmentVariableBag
        execution:
          onExecute:
            - mkdir -p bin
            - cp -vr $res_myFileSpecRes_resourcePath/folder1/folder2/example-{{gitBranch}}.tar.gz ./bin/example.tar.gz
            - echo "some logic to deploy"
            
