resources:
  - name: my_resource
    type: Image
    configuration:
      registry: deepikaArt
      sourceRepository: deepika-virtual
      imageName: docker.io/selenium/standalone-chrome
      imageTag: '86.0'
      autoPull: true
pipelines:
  - name: deepika_test
    steps:
      - name: step_1_deepika
        type: Bash
        configuration:
          inputResources:
            - name: my_resource
        execution:
          onExecute:
            - echo "executingg"
            
