print-5-numbers: &print-5-numbers
  - echo 1
  - echo 2
  - echo 3
  - echo 4
  - echo 5
  
resources:
  - name: myRepo
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master

pipelines:
  - name: demo_manual
    configuration:
      integrations:
        - name: deepikaGithub
    steps:
      - name: manual_trigger
        type: Bash
        configuration:
          inputResources:
            - name: myRepo
        execution:
          onExecute:
            - *print-5-numbers
 
