resources:
  - name: myRepo
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master

  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: demo_manual
    configuration:
      integrations:
        - name: deepikaGithub
    steps:
      - name: first_step
        type: Bash          
        execution:
          onExecute:
            - echo "first_step"
      - name: second_step
        type: Bash   
        configuration:
          inputSteps:
            - name: first_step
        execution:
          onExecute:
            - echo "first_step"
      - name: third_step
        type: MvnBuild
        configuration:
          condition: '{{gitBranch}} == master'
          resolverSnapshotRepo: libs-snapshot
          resolverReleaseRepo: libs-release
          deployerSnapshotRepo: libs-snapshot-local
          deployerReleaseRepo: libs-release-local
          mvnCommand: clean install -ntp
          sourceLocation: backend
          inputSteps:
            - name: second_step
          integrations:
            - name: deepikaArt
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version
            - mvn --version
          
            
