template: true     
valuesFilePath: ./values.yml

resources:
  - name: myRepo
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: {{ .Values.GitRepo.gitProvider }}
      branches:
        include: master

  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: demo_manual
    configuration:
      integrations:
        - name: deepikaGithub
    steps:
      - name: manual_trigger
        type: Bash
        configuration:
          inputResources:
            - name: myRepo
          outputResources:
            - name: propertyBag
          integrations:
            - name: deepikaGithub
        execution:
          onStart:
            - |
              if [ "{{gitBranch}}" = "main" ]; then
                echo "Branch is 'main'"
              fi
          onExecute:
            - write_output propertyBag "foo=$run_number"
            
