valuesFilePath: ./values.yml
resources:  
  - name: goTemplateBinary
    type: FileSpec
    configuration:
      sourceArtifactory: art
      pattern: "deepika-artifacts/pipelines-template"
      recursive: false
      flat: true

pipelines:
  - name: {{ .Values.release_template.pipelineName }}
    configuration:
      environmentVariables:
        readOnly:
          templateTarget: {{ .Values.release_template.path }}
          version: {{ .Values.release_template.version }}
    steps:
      - name: {{ .Values.release_template.stepName }}
        type: Bash
        configuration:
          integrations:
            - name: {{ .Values.git_integration_name }}
        execution:
          onExecute:
              - providerUrl=$int_{{.Values.git_integration_name}}_url
              - repositoryUrl=$providerUrl/repos/$repoPath
              - |
                normalizeRepoResult=$(curl --location --request GET 'https://api.github.com/repos/deepikasl/monoRepository' \
                  --header 'Accept: application/vnd.GithubProvider.v3' \
                  --header 'Authorization: token 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' \
                  --header 'Content-Type: application/json' \
                  --data-raw '')
              - mkdir -p cloneRepo
              - pushd cloneRepo
              - git clone $normalizeRepoResult.clone_url
              - pushd $repoName
              - ls
              - popd
              
