resources:
  - name: myRepo
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master

  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: demo_manual
    configuration:
      integrations:
        - name: deepikaGithub
    steps:
      - name: first_step
        type: Bash          
        execution:
          onExecute:
            - echo "first_step"
      - name: second_step
        type: Bash   
        configuration:
          inputSteps:
            - name: first_step
        execution:
          onExecute:
            - echo "first_step"
      - name: third_step
        type: MvnBuild
        configuration:
          condition: '{{gitBranch}} == master'
          inputSteps:
            - name: second_step
        execution:
          onExecute:
            - write_output propertyBag "foo=$run_number"
            
