resources:
  - name: myRepo
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master
  
  - name: tempRepo
    type: GITRepo
    configuration:
      path: deepikasl/old-templates
      gitProvider: deepikaGithub
      branches:
        include: master

  - name: myTemplate
    type: FileSpec
    configuration:
      sourceArtifactory: art
      pattern: "deepika-artifacts/pipelines-template"
      recursive: false
      flat: true

pipelines:
  - name: Demo_template
    steps:
      - name: validate_template
        type: Bash
        configuration:
          inputResources:
            - name: myTemplate
            - name: tempRepo
        execution:
          onExecute:
            - pushd $res_tempRepo_resourcePath
            - pushd templates/jfrog_name_space/myPipelineTemplate
            - touch values.yml
            - cp -vr $res_myTemplate_resourcePath/pipelines-template ./pipelines-template
            - chmod +x ./pipelines-template
            - ./pipelines-template apply --values-file ./values.yml --template-file ./templateDefinition.yml --output-file output.yml
            - cat output.yml
            - popd
            
