resources:
  - name: r_9623_propertyBag_store
    type: PropertyBag
    configuration:
      storeVersionHistory: true
      myEnv: 1

  - name: r_9623_propertyBag_no_store
    type: PropertyBag
    configuration:
      storeVersionHistory: false
      myEnv: 1

pipelines:
  - name: pipeline_9623
    steps:
      - name: step_9623_1
        type: Bash
        configuration:
          outputResources:
            - name: r_9623_propertyBag_store
            - name: r_9623_propertyBag_no_store
        execution:
          onExecute:
            - write_output r_9623_propertyBag_store "myEnv=$run_number"
            - write_output r_9623_propertyBag_no_store "myEnv=$run_number"
