resources:
  - name: myRepo
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master

  - name: myTemplate
    type: FileSpec
    configuration:
      sourceArtifactory: art
      pattern: "pipelines-artifacts/pipelines-template"
      recursive: false
      flat: true

pipelines:
  - name: Demo_template
    steps:
      - name: validate_template
        type: Bash
        configuration:
          inputResources:
            - name: myTemplate
        execution:
          onExecute:
            - echo "you are here"
            
