resources:
  - name: my_resource_1
    type: Image
    configuration:
      registry: deepikaArt
      sourceRepository: deepika-virtual-docker
      imageName: selenium/standalone-chrome
      imageTag: '86.0'
      autoPull: true
pipelines:
  - name: deepika_test
    steps:
      - name: step_1_deepika
        type: Bash
        configuration:
          inputResources:
            - name: my_resource_1
        execution:
          onExecute:
            - echo "executingg"
            
