template: true
resources:  
  - name: goTemplateBinary
    type: FileSpec
    configuration:
      sourceArtifactory: art
      pattern: "deepika-artifacts/pipelines-template"
      recursive: false
      flat: true

pipelines:
  - name: {{ .Values.release_template.pipelineName }}
    configuration:
      environmentVariables:
        readOnly:
          templateTarget: {{ .Values.release_template.path }}
          version: {{ .Values.release_template.version }}
    steps:
      - name: {{ .Values.release_template.stepName }}
        type: Bash
        configuration:
          integrations:
            - name: {{ .Values.git_integration_name }}
        execution:
          onExecute:
              - providerUrl=$int_{{.Values.git_integration_name}}_url
              - repositoryUrl=$providerUrl/repos/$repoPath
              
