resources:
  - name: newRepo
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master
  - name: propertyBag_1
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: demo_manual_1
    steps:
      - name: manual_trigger_1
        type: Bash
        configuration:
          inputResources:
            - name: newRepo
          outputResources:
            - name: propertyBag_1
          integrations:
            - name: deepikaGithub
        execution:
          onExecute:
            - write_output propertyBag "foo=$run_number"
